name: Push to Github docker registry (Manual)
on:
    workflow_dispatch:
        inputs:
            image_tag:
                type: string
                description: 'Image tag'
                required: true
                default: 'latest'

jobs:
    build-and-publish:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Login to registry
              uses: docker/login-action@v2
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GH_PAT }}

            - name: Build image
              run: |
                  docker build -t ghcr.io/${{ github.repository }}:${{ inputs.image_tag }} .

            - name: Push Docker image
              run: |
                  docker push ghcr.io/${{ github.repository }}:${{ inputs.image_tag }}
